const L={airbnb:'Airbnb',booking:'Booking',vrbo:'Vrbo'},ch={airbnb:[],booking:[],vrbo:[]};
let dp={},selectedDay=null,viewMonth=null;
let C=[{id:'709922361709636053',br:2,spa:'нет',avg:'',use:true},{id:'1524788241930455500',br:1,spa:'есть',avg:'',use:false},{id:'975753671574656503',br:1,spa:'включён',avg:'',use:false},{id:'551120683766819625',br:1,spa:'включён',avg:'',use:false},{id:'864856748392207533',br:1,spa:'есть',avg:'',use:false},{id:'1413524494264554969',br:1,spa:'есть',avg:'',use:false}];
const $=x=>document.getElementById(x);
function ymd(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function fromYMD(s){const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}
function num(x){return parseFloat($(x).value)||0}
function median(a){if(!a.length)return null;a=[...a].sort((x,y)=>x-y);const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function ics(t,s){t=t.replace(/\r?\n[ \t]/g,'');const out=[];for(const c of t.split('BEGIN:VEVENT').slice(1)){const b=c.split('END:VEVENT')[0];if(/STATUS:CANCELLED/i.test(b))continue;const a=(b.match(/DTSTART(?:;[^:]*)?:(\d{8})/)||[])[1],z=(b.match(/DTEND(?:;[^:]*)?:(\d{8})/)||[])[1];if(a&&z){const f=q=>q.slice(0,4)+'-'+q.slice(4,6)+'-'+q.slice(6,8);out.push({start:f(a),end:f(z),source:s})}}return out}
function range(a,z){const r=[];let d=fromYMD(a),e=fromYMD(z);while(d<e){r.push(ymd(d));d.setDate(d.getDate()+1)}return r}
function bm(){const m={};for(const [s,es] of Object.entries(ch))for(const e of es)for(const d of range(e.start,e.end))(m[d]??=[]).push(s);return m}
function occ(m,st,n){let c=0,d=fromYMD(st);for(let i=0;i<n;i++){if(m[ymd(d)])c++;d.setDate(d.getDate()+1)}return c/n}
function isGap(day,m){if(m[day])return false;const d=fromYMD(day),p=new Date(d),n1=new Date(d),n2=new Date(d);p.setDate(p.getDate()-1);n1.setDate(n1.getDate()+1);n2.setDate(n2.getDate()+2);return !!m[ymd(p)]&&(!!m[ymd(n1)]||!!m[ymd(n2)])}
function market(day){const v=[];for(const c of C.filter(x=>x.use)){const q=dp[day]?.[c.id],a=parseFloat(c.avg);if(Number.isFinite(q)&&q>0)v.push(q);else if(Number.isFinite(a)&&a>0)v.push(a)}return median(v)}
function price(day,m,o){const d=fromYMD(day),mo=d.getMonth()+1;let p=num('base'),why=[];const mult=[12,1,2,3].includes(mo)?num('win'):[7,8].includes(mo)?num('sum'):num('sho');p*=mult;why.push(mult>1?'season ↑':'season ↓');if([5,6].includes(d.getDay())){p*=1+num('wk')/100;why.push('weekend')}const t=new Date();t.setHours(0,0,0,0);const lead=Math.round((d-t)/86400000);if(lead>=0&&lead<7){p*=1+num('lm')/100;why.push('last-minute')}if(o>.7){p*=1+num('ho')/100;why.push('high occ')}if(isGap(day,m)){p*=1+num('gap')/100;why.push('gap')}const mk=market(day);if(mk!==null&&num('mw')>0){const w=Math.max(0,Math.min(100,num('mw')))/100,target=mk*(1+num('mt')/100);p=p*(1-w)+target*w;why.push('market '+(num('mt')>=0?'+':'')+num('mt')+'%')}return{p:Math.round(Math.max(num('floor'),p)),m:mk===null?null:Math.round(mk),why}}
function save(){localStorage.setItem('brmC',JSON.stringify(C));localStorage.setItem('brmCh',JSON.stringify(ch));localStorage.setItem('brmDP',JSON.stringify(dp));for(const id of ['base','floor','wk','lm','ho','gap','win','sum','sho','mw','mt','start','days'])localStorage.setItem('brm-'+id,$(id).value)}
function restore(){const c=JSON.parse(localStorage.getItem('brmC')||'null');if(c)C=c;const h=JSON.parse(localStorage.getItem('brmCh')||'null');if(h)Object.assign(ch,h);dp=JSON.parse(localStorage.getItem('brmDP')||'{}');for(const id of ['base','floor','wk','lm','ho','gap','win','sum','sho','mw','mt','start','days']){const v=localStorage.getItem('brm-'+id);if(v!==null)$(id).value=v}}
